### PR TITLE
Add Algolia search to the desktop version

### PR DESCRIPTION
**Pull request by AbderrahimSoubaiElidrissi**
Hello 

## Context

Related to #180 I added a search box powered by Algolia (attached picture)

image

## How it works 

On build time gatsby generate data (via `graphQL` queries) and send it to Algolia to be indexed on typeahead `gatsby-plugin-algolia` catch the user query and via `algoliasearch` client gatsby send a request to Algolia and get the search `Hits`

## Requirement:

- Free Algolia account -[ create one](https://www.algolia.com/users/sign_up)
- Create an new Index : `Blablas`
- Add the follow value to `.env` file (Check `.env.example`) :
```
GATSBY_ALGOLIA_APP_ID=<App ID>
GATSBY_ALGOLIA_SEARCH_KEY=<Search-Only API Key>
ALGOLIA_ADMIN_KEY=<Admin API Key>
```
The following values are in `API Keys` section (See the sidebar)

**The ALGOLIA_ADMIN_KEY should be not exposed on the code need to be added to Netilify secrets**

# Todo 
- Add support to the mobile version (Now the only desktop version is supported)

### CODE REVIEW

**Comment by yjose** [comment]
Working as expected, thank you @AbderrahimSoubaiElidrissi , not sure about the design part  @ismailElazizi  any thoughts?

**Comment by AbderrahimSoubaiElidrissi** [comment]
Let's placeholder it and wait for Ismail feedback

**Comment by aboullaite** [comment]
Nice feature! Thanks @AbderrahimSoubaiElidrissi for putting this together

**Comment by makraz** [comment]
Awesome, thanks @AbderrahimSoubaiElidrissi

**Comment by yjose** [comment]
@AbderrahimSoubaiElidrissi i don't have enough experience with algolia but look like we are creating a new record for every episode,  would like to know if we can create a record for every note and on click would redirect you to the exact note time.
Do you think this is something we can do with algolia free account?

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose @aboullaite @makraz @ismailElazizi  As the Algolia free account limits are 10K Reqs/month I don't think so it a good idea to let users go that deep in the global search input (the one in the header). Technically speaking we can do the same for notes ( split the note to lines identified by `timestamp` ) but I will vote for the solution to keep a global search for episodes (search in title + notes) and add search input above the note card  powered only by typeahead feature and using javascript to search in the note.

**Comment by makraz** [comment]
> @yjose @aboullaite @makraz @ismailElazizi As the Algolia free account limits are 10K Reqs/month I don't think so it a good idea to let users go that deep in the global search input (the one in the header). Technically speaking we can do the same for notes ( split the note to lines identified by `timestamp` ) but I will vote for the solution to keep a global search for episodes (search in title + notes) and add search input above the note card powered only by typeahead feature and using javascript to search in the note.

+1

**Comment by yjose** [comment]
ok noted, @AbderrahimSoubaiElidrissi  for UI Part, I would suggest using a modal style for search cmpoenent like https://docusaurus.io/ , I can work on it this weekend if you don't have time to do it.

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose I can give it a try this weekend I will keep you in touch in cases I didn't found a time to do it

**Comment by AbderrahimSoubaiElidrissi** [comment]
Added these changes: 

- Modal search
- handle no result
- navbar search button + icon

image

Todo:
- responsiveness 
- some custom animation
- Clean up the code 
@yjose feel free If you want to fix those missing points or add/change something

**Comment by yjose** [comment]
Great @AbderrahimSoubaiElidrissi , can you push your updates

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose Done

**Comment by yjose** [comment]
Great, as you are planning to add animation to the modal, I am not sure if react modal is the best choice and as we already using reactjs-popup to implement modal in the project 😀, I think no need for two solutions that do the same thing , let me know what you think?

also, I would recommend updating the search input place next to the dark mode button , last item in the right

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose I totally forget about react-popup as a modal solution and for react-modal, I found it already installed on the project. I will update the modal to react-popup since you can help in cases of issues :laughing: .

I will work on this as soon as I have some free time

**Review by yjose — APPROVED** [review]
👍

**Pull request merged**
