### PR TITLE
fix: social channels space

### PR DESCRIPTION
**Pull request by faissaloux**
Give social  icons some space to breathe 😮‍💨 

# Before
Screenshot from 2021-09-23 15-37-08

# After
Screenshot from 2021-09-23 15-37-24

### CODE REVIEW

**Comment by yjose** [comment]
thanks @faissaloux for your contribution, not sure if your solution would work on a mobile device 
Using `50%` in mobile screen would break the section

**Comment by faissaloux** [comment]
@yjose Actually no, it wouldn't break anything.

But I'll increase `50%` to `80%`  for mobile screen to add more space between icons

**Comment by faissaloux** [comment]
# Desktop
Screenshot from 2021-10-04 16-08-52

# Mobile
Screenshot from 2021-10-04 16-10-05

**Comment by yjose** [comment]
@faissaloux  looks good now

**Review by yjose — APPROVED** [review]
👍

**Pull request merged**
