### PR TITLE
[Fix] Display issue when the note's time is in format hh:mm:ss 

### PR DESCRIPTION
**Pull request by Kafiil**
This is supposed to solve #111

### CODE REVIEW

**Comment by aboullaite** [comment]
In my PoV we should keep the hh:mm format, it's shorter and simpler and unify it (updating contributing guide to mention it, and verify it in PRs) WDYT Youssouf?

**Comment by Kafiil** [comment]
Even if you do, this handles both cases. In case some value slippeded. This makes sure that is displays correctly

**Comment by yjose** [comment]
I just checked episodes Notes and Look like we only have this problem in the 5 first Episodes, So @Kafiil  I think it would be better if you update episodes Note instead 🙏.

@aboullaite we did add an example in the contributing Guide but I think I need to mention it explicitly.

**Comment by Kafiil** [comment]
You rather correct all the episode that change a line in code that can handle this ? I really don't get it.

**Comment by yjose** [comment]
this problem is not related to support multiple formats. your fix will not work with such a problem.
check this episode as an example:  https://deploy-preview-112--geeksblabla.netlify.com/blablas/devops

And try to click to `47:53 IDE (Toolchain)`, will not work for sure because `47` it's the minute instead of the Hour.

So There is No way to fix the issue without updating Notes.

**Comment by Kafiil** [comment]
The person who made this used `mm:ss` instead of `hh:mm`, which is another issue that I am not addressing in this commit.

My fix handles using `hh:mm:ss` and `hh:mm `without breaking the ui

**Comment by yjose** [comment]
Yeah correct, but I think if we fix the  issue related to incorrect format. We won't need tohandle hh:mm:ss format in the first place.

**Comment by Kafiil** [comment]
Correct, but still `hh:mm:ss` is more precise than `hh:mm`

**Comment by yjose** [comment]
Yeah, But unfortunately we already decide to use this format because it's shorter and simpler for our contributors.

**Comment by yjose** [comment]
#113

**Pull request closed without merging**
