### PR TITLE
Incorrect time format fix for some episodes

### PR DESCRIPTION
**Pull request by zakariaelas**
Episodes fixed: 1, 6, 7, 12, 13, 15
#113

### CODE REVIEW

**Comment by yjose** [comment]
@zakariaelas  👍 , Can you please Make a tour and Make sure we didn't miss any incorrect format in other episodes🙏

**Comment by zakariaelas** [comment]
Alright i'm on it :+1: !

**Comment by zakariaelas** [comment]
Double checked the other episodes at the best of my ability, and it seems like the other episodes are all good. Fixed a minor typo.

**Comment by yjose** [comment]
@all-contributors please add @zakariaelas  for content

**Pull request merged**
