### PR TITLE
review: removing my review

### PR DESCRIPTION
**Pull request by smakosh**

### CODE REVIEW

**Comment by yjose** [comment]
@smakosh  why?

**Comment by smakosh** [comment]
> @smakosh why?

It looks like my opinion was remove from here: https://youtu.be/ts4P4AGxD94

**Comment by yjose** [comment]
@smakosh it's ok, i don't think it's a problem that requires removing your review. the team behind snippets is doing a great job of making short videos and they try to make videos as short as possible. it's up to the team to decide the best parts and the right duration.  

let me know what you think?

**Comment by smakosh** [comment]
I disagree & wish to get my review removed.

**Comment by yjose** [comment]
ok, can you remove the image too?

**Comment by smakosh** [comment]
Done @yjose

**Pull request merged**
