### PR TITLE
GeeksBlabla V2

### PR DESCRIPTION
**Pull request by yjose**
New Geeks Balabla Version With :
* New design with a Landing Page : 
     - Add Reviews Section
     - Add New Home page section for episodes types ( MSS & Tech) 
     - Add Reviews Section 
* Optimize Blabla Page: 
      - New scrolling experience. 
      - New Markdown styling for episodes Notes. 
      -  Add Share Buttons. 
      - Custom social Media sharing Image.
* Add Contributors list to About Page. 
* Fix Facebook Player issues. 
* Add push Notification #44 
* Fix issues  #63 #64 #19 #47 #57
* Reviews Section
* PWA READY

### CODE REVIEW

**Comment by aboullaite** [comment]
Brilliant work @yjose ! I love the new design! keep it up

**Comment by melbarch** [comment]
wow nice work @yjose !

**Comment by yjose** [comment]
@souffanda, @aboullaite  PR Ready for merge, need a final review.

**Comment by aboullaite** [comment]
I prefer to put testemonials section in one carousel, with max 6/7 testemonials!

**Comment by yjose** [comment]
@aboullaite  Done !

**Pull request merged**
